
a = open("hello.txt", 'w')
a.write("hello\n")  
a.close()
a=open("hello.txt",'a')
a.write("hi")
a.close()
a = open("hello.txt", 'r')
b = a.read()
print(b)  
a.close()
x = open("hi.txt", 'w')
x.write(input("enter:"))
x.close()
